import { showKbOrder, showKb } from '../../lib/display'
import { 
  baseAPIUrl, 
} from '../../lib/apiService';

const SummaryGeneration = (set, get) => {

  // generate query from narration for summary
  const generateQueryFromNarration = (narration) => {
    let order = Math.max(...narration.path.map(d => d.order))
    let scale = showKb(4 ** (14 - order)).join("") + " SCALE"
    
    let fields = narration.path.filter(d => {
      if(d.layer?.datasetName?.indexOf("occ") > -1) {
        return d.field?.value > 0.75
      } else if(d.layer?.datasetName?.indexOf("gwas") > -1 || d.layer?.datasetName?.indexOf("ukbb_94") > -1) {
        return true
      } else {
        // return d.field?.value > 2
        return d.field?.value > 0.25
      }
    })
    .sort((a,b) => b.field?.value - a.field?.value)
    .map(d => {
      // Determine the data type based on layer name
      let prefix = ""
      if (d.layer?.datasetName?.toLowerCase().includes("tf_")) {
        prefix = "MOTIF"
      } else if (d.layer?.datasetName?.toLowerCase().includes("dhs_")) {
        prefix = "DHS"
      } else if (d.layer?.datasetName?.toLowerCase().includes("cs_")) {
        prefix = "CS"
      } else if (d.layer?.datasetName?.toLowerCase().includes("repeat")) {
        prefix = "REPEAT"
      } else if (d.layer?.datasetName?.toLowerCase().includes("ukbb")) {
        prefix = "GWAS"
      }
      let enrocc = ""
      if(d.layer?.datasetName?.toLowerCase().includes("enr")) {
        enrocc = "domain"
      } else if(d.layer?.datasetName?.toLowerCase().includes("occ")) {
        enrocc = "occurrence"
      }
      
      // Format with resolution if available
      const resolution = `@ ${showKbOrder(d.order)}`.replace(",", "")
      return `${d.field?.field} ${prefix} ${enrocc} ${resolution}`
    })

    let genes = narration.genes ? narration.genes.map(d => d.in_gene ? `GENE_OVL ${d.name}` : `GENE_ADJ ${d.name}`) : []
    let geneNames = narration.genes ? narration.genes.map(d => d.name) : []
    // // Sort genesets by p-value (region set p-values) and take top 3
    // let filteredGenesets = narration.genesets?.filter(d => d.p).sort((a,b) => a.p - b.p)?.slice(0, 3)
    // // If no genesets with p-values, take first 3 genesets
    // let genesets = (filteredGenesets?.length > 0 ? filteredGenesets : narration.genesets?.slice(0, 3))
    //   ?.map(d => {
    //     const term = d.geneset.split('_').slice(1).join(' ')
    //     return `GO ${term.toUpperCase()}`
    //   })
    // if(!fields.length && !genesets.length && !genes.length) return null;

    // Sort genesets by p-value (region set p-values)
    let filteredGenesets = narration.genesets?.filter(d => d.p).sort((a,b) => a.p - b.p)
    // If no genesets with p-values (ie no region set), use all
    let genesets = (filteredGenesets?.length > 0 ? filteredGenesets : narration.genesets)
      ?.map(d => {
        const term = d.geneset.split('_').slice(1).join(' ')
        // only relevant genes are included as tags for the genesets
        const termGenes = d.genes.filter(g => geneNames.includes(g))
        return `GO ${term.toUpperCase()} (${termGenes.join(", ")})`
      })
    if(!fields.length && !genesets.length && !genes.length) return null;

    // Combine all parts with semicolons
    let query = [scale, ...fields, ...genes, ...(genesets || [])].join("; ")

    return query
  }

  // generates a summary for the selected region
  const generateSummaryFromQuery = (providedPrompt = null) => {
    let p = providedPrompt || get().prompt
    let query = get().query
    if(query !== "") {
      return fetch(`${get().url}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          query: query,
          narration: get().selectedNarration,
          prompt: p
        })
      })
      .then(res => {
        return res.json()
      })
      .then(data => {
        // console.log("generate", data, query)
        return data;
      })
      .catch(err => {
        console.error(err)
        return null;
      })
    } 
    return null;
  }

  // Function to provide feedback to the model
  const feedback = (feedback) => {
    let url_feedback = get().url_feedback
    let request_id = get().request_id
    fetch(`${url_feedback}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        request_id: request_id,
        feedback: feedback,
      })
    })
      .then(res => res.json())
      .then(data => {
        console.log("feedback", data)
      })
      .catch(err => {
        console.error(err)
      })
  }

  const termsSection = `You are an expert genomics researcher, tasked with narrating genomic regions such that a single short sentence captures the most important information.
  You are given a query consisting of a term-wise description of a certain region of interest in the human genome.

  These terms may include things like chromatin state calls (CS), DNase I Hypersensitive Site annotations (DHS), transcription factor motif hits (MOTIF), interspersed repeats and low complexity DNA sequences (REPEAT), and Genome-Wide Association Study traits (GWAS).
  All such terms are observed at a certain genomic scale, ranging from a single basepair (1bp) to a million basepair (1Mbp).
  They are listed in the query in descending order of prominence, so make sure to take that into account in prioritizing the information to use in your narration.
  Furthermore, the genomic region of interest may directly overlap an observed term ('occurrence'), or may overlap a larger region with an abundance of that term ('domain') in which there is not necessarily a direct overlap with a single instance of the term. This is an important distinction.

  The size (SCALE) of the region the narration will be generated for is also provided, make sure to state the region's size in your summary.
  Additionally, you are provided information on any genes that directly overlap (GENE_OVL) or are adjacent to (GENE_ADJ) the region.
  To aid in functional narration, you are also provided with Gene Ontology genesets (GO) associated with the region (along with a tag of the overlapping or adjacent genes that belong to each geneset), which may constitute important information in combination with all of the above.
  If you choose to highlight a geneset, make sure the genes you highlight in addition are members of the geneset.
  `

  const abstractsAccess = `You also have access to titles and abstracts of research articles that may be relevant to the query, so make sure to use these for additional context and writing style.
  `

  const tastSection = `Your task is to generate a helpful one-sentence summary of the query, providing a useful narrative of the genomic region.
  If any of the provided terms do not seem relevant according to literature or otherwise, feel free to skip them in the narrative.
  `

  const examplesSection = `Examples
  --------
  Query: "1bp SCALE; EWSR1/FLI1 MOTIF domain @ 16kbp; Stromal B DHS domain @ 1Mbp; Atrial fibrillation GWAS  @ 1bp; Musculoskeletal DHS domain @ 64kbp; Cardiac DHS domain @ 256kbp; Quiescent/Low CS domain @ 1kbp; GENE_ADJ NTMT2; GENE_ADJ GORAB; GO SKIN DEVELOPMENT (GORAB); GO SKIN EPIDERMIS DEVELOPMENT (GORAB); GO METHYLATION (NTMT2); GO CELL PROJECTION ORGANIZATION (GORAB); GO PROTEIN METHYLATION (NTMT2); GO CELL PROJECTION ASSEMBLY (GORAB); GO MORPHOGENESIS OF AN EPITHELIUM (GORAB); GO EPIDERMIS DEVELOPMENT (GORAB); GO EPIDERMIS MORPHOGENESIS (GORAB); GO MACROMOLECULE METHYLATION (NTMT2); GO NON MOTILE CILIUM ASSEMBLY (GORAB); GO N TERMINAL PROTEIN AMINO ACID MODIFICATION (NTMT2); GO ORGANELLE ASSEMBLY (GORAB); GO REGULATION OF SMOOTHENED SIGNALING PATHWAY (GORAB); GO TISSUE MORPHOGENESIS (GORAB); GO POSITIVE REGULATION OF SIGNALING (GORAB); GO MOLTING CYCLE PROCESS (GORAB); GO MOLTING CYCLE (GORAB); GO EPITHELIUM DEVELOPMENT (GORAB); GO SMOOTHENED SIGNALING PATHWAY (GORAB); GO POSITIVE REGULATION OF SMOOTHENED SIGNALING PATHWAY (GORAB); GO CILIUM ORGANIZATION (GORAB)",
  Summary: "This single base pair is a likely causal atrial fibrillation GWAS variant, found inside a cardiac DHS as part of a much larger cardiac and musculoskeletal DHS domain"
  Query: "1bp SCALE; PLAG1 MOTIF domain @ 64kbp; Satellite REPEAT domain @ 1Mbp; HINFP1/3 MOTIF domain @ 256kbp; KLF/SP/2 MOTIF domain @ 16kbp; Ebox/CACGTG/1 MOTIF domain @ 4kbp; Mean corpuscular hemoglobin GWAS  @ 1bp; Myeloid / erythroid DHS occurrence @ 256bp; GENE_ADJ NKD2; GENE_OVL SLC12A7; GO POTASSIUM ION HOMEOSTASIS (SLC12A7); GO CANONICAL WNT SIGNALING PATHWAY (NKD2); GO POTASSIUM ION IMPORT ACROSS PLASMA MEMBRANE (SLC12A7); GO REGULATION OF PROTEIN LOCALIZATION TO CELL PERIPHERY (NKD2); GO HOMEOSTATIC PROCESS (SLC12A7); GO POTASSIUM ION TRANSPORT (SLC12A7); GO CHEMICAL HOMEOSTASIS (SLC12A7); GO REGULATION OF CELL SIZE (SLC12A7); GO PROTEIN CATABOLIC PROCESS (NKD2); GO NEGATIVE REGULATION OF CANONICAL WNT SIGNALING PATHWAY (NKD2); GO MEMBRANE FUSION (NKD2); GO CARBOHYDRATE HOMEOSTASIS (SLC12A7); GO POSITIVE REGULATION OF GENE EXPRESSION (NKD2); GO RESPONSE TO OXYGEN CONTAINING COMPOUND (SLC12A7); GO RESPONSE TO CARBOHYDRATE (SLC12A7); GO GOLGI VESICLE TRANSPORT (NKD2); GO REGULATION OF CANONICAL WNT SIGNALING PATHWAY (NKD2); GO ORGANONITROGEN COMPOUND CATABOLIC PROCESS (NKD2); GO NEGATIVE REGULATION OF WNT SIGNALING PATHWAY (NKD2); GO PROTEIN LOCALIZATION TO PLASMA MEMBRANE (NKD2); GO NITROGEN COMPOUND TRANSPORT (SLC12A7); GO CELL CELL SIGNALING (SLC12A7); GO AMMONIUM TRANSMEMBRANE TRANSPORT (SLC12A7); GO TRANSMEMBRANE TRANSPORT (SLC12A7); GO REGULATION OF CATABOLIC PROCESS (NKD2); GO REGULATION OF PROTEASOMAL PROTEIN CATABOLIC PROCESS (NKD2); GO REGULATION OF ANATOMICAL STRUCTURE SIZE (SLC12A7); GO IMPORT ACROSS PLASMA MEMBRANE (SLC12A7); GO IMPORT INTO CELL (SLC12A7); GO ORGANELLE MEMBRANE FUSION (NKD2); GO WNT SIGNALING PATHWAY (NKD2); GO ORGANELLE FUSION (NKD2); GO PROTEIN MATURATION (NKD2); GO REGULATION OF PROTEIN CATABOLIC PROCESS (NKD2); GO REGULATION OF PROTEASOMAL UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (NKD2); GO INORGANIC ANION TRANSMEMBRANE TRANSPORT (SLC12A7); GO MODIFICATION DEPENDENT MACROMOLECULE CATABOLIC PROCESS (NKD2); GO INORGANIC ION HOMEOSTASIS (SLC12A7); GO REGULATION OF PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (NKD2); GO PROTEIN PROCESSING (NKD2); GO POSITIVE REGULATION OF PROTEIN METABOLIC PROCESS (NKD2); GO POSITIVE REGULATION OF PROTEIN MATURATION (NKD2); GO POSITIVE REGULATION OF PROTEIN LOCALIZATION TO PLASMA MEMBRANE (NKD2); GO PROTEIN LOCALIZATION TO CELL PERIPHERY (NKD2); GO POSITIVE REGULATION OF PROTEIN CATABOLIC PROCESS (NKD2); GO POSITIVE REGULATION OF PROTEIN LOCALIZATION TO MEMBRANE (NKD2); GO CELLULAR RESPONSE TO ORGANIC SUBSTANCE (SLC12A7); GO MONOATOMIC ANION HOMEOSTASIS (SLC12A7); GO MONOATOMIC ANION TRANSPORT (SLC12A7); GO REGULATION OF PROTEOLYSIS (NKD2); GO MONOATOMIC CATION TRANSMEMBRANE TRANSPORT (SLC12A7); GO MONOATOMIC CATION TRANSPORT (SLC12A7); GO POSITIVE REGULATION OF PROTEIN LOCALIZATION (NKD2); GO MONOATOMIC ION HOMEOSTASIS (SLC12A7); GO NEGATIVE REGULATION OF RESPONSE TO STIMULUS (NKD2); GO MONOATOMIC ION TRANSMEMBRANE TRANSPORT (SLC12A7); GO MONOATOMIC ION TRANSPORT (SLC12A7); GO SYNAPTIC SIGNALING (SLC12A7); GO POSITIVE REGULATION OF UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (NKD2); GO CELLULAR RESPONSE TO OXYGEN CONTAINING COMPOUND (SLC12A7); GO POSITIVE REGULATION OF CATABOLIC PROCESS (NKD2); GO CELLULAR RESPONSE TO CARBOHYDRATE STIMULUS (SLC12A7); GO POSITIVE REGULATION OF PROTEIN LOCALIZATION TO CELL PERIPHERY (NKD2); GO POSITIVE REGULATION OF PROTEASOMAL UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (NKD2); GO POSITIVE REGULATION OF PROTEASOMAL PROTEIN CATABOLIC PROCESS (NKD2); GO CELL VOLUME HOMEOSTASIS (SLC12A7); GO INORGANIC ION IMPORT ACROSS PLASMA MEMBRANE (SLC12A7); GO MACROMOLECULE CATABOLIC PROCESS (NKD2); GO MEMBRANE ORGANIZATION (NKD2); GO REGULATION OF CELLULAR COMPONENT SIZE (SLC12A7); GO REGULATION OF PROTEIN LOCALIZATION TO MEMBRANE (NKD2); GO REGULATION OF CELLULAR LOCALIZATION (NKD2); GO PROTEASOME MEDIATED UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (NKD2); GO REGULATION OF PROTEIN LOCALIZATION TO PLASMA MEMBRANE (NKD2); GO NEGATIVE REGULATION OF SIGNALING (NKD2); GO CELLULAR HOMEOSTASIS (SLC12A7); GO VESICLE ORGANIZATION (NKD2); GO REGULATION OF PROTEIN MATURATION (NKD2); GO PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (NKD2); GO PROTEOLYSIS (NKD2); GO VESICLE MEDIATED TRANSPORT (NKD2); GO PROTEASOMAL PROTEIN CATABOLIC PROCESS (NKD2); GO LOCALIZATION WITHIN MEMBRANE (NKD2); GO EXOCYTOSIS (NKD2); GO CHLORIDE TRANSPORT (SLC12A7); GO SECRETION (NKD2); GO POSITIVE REGULATION OF PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (NKD2); GO POSITIVE REGULATION OF PROTEOLYSIS (NKD2); GO EXPORT FROM CELL (NKD2); GO REGULATION OF WNT SIGNALING PATHWAY (NKD2); GO INTRACELLULAR GLUCOSE HOMEOSTASIS (SLC12A7); GO INORGANIC ANION TRANSPORT (SLC12A7); GO REGULATION OF UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (NKD2)",
  Summary: "This single base pair is a likely causal red blood cell GWAS variant, found inside a myeloid/erythroid DHS contained in an active enhancer element."
  Query: "256bp SCALE; Lymphoid DHS domain @ 16kbp; IRF/2 MOTIF domain @ 4kbp; NRF1 MOTIF domain @ 1Mbp; ZNF320 MOTIF domain @ 256kbp; SREBF1 MOTIF domain @ 64kbp; KLF/SP/2 MOTIF domain @ 1kbp; GENE_ADJ CCDC22; GENE_OVL FOXP3; GO IMMATURE T CELL PROLIFERATION (FOXP3); GO IMMUNOGLOBULIN PRODUCTION (FOXP3); GO T CELL DIFFERENTIATION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO DEFENSE RESPONSE TO VIRUS (FOXP3); GO T CELL DIFFERENTIATION IN THYMUS (FOXP3); GO GOLGI VESICLE TRANSPORT (CCDC22); GO T CELL HOMEOSTASIS (FOXP3); GO IMMUNE SYSTEM DEVELOPMENT (FOXP3); GO REGULATION OF HEMOPOIESIS (FOXP3); GO REGULATION OF CELL ADHESION (FOXP3); GO T CELL LINEAGE COMMITMENT (FOXP3); GO DEFENSE RESPONSE TO OTHER ORGANISM (FOXP3); GO IMMUNE EFFECTOR PROCESS (FOXP3); GO REGULATION OF DNA RECOMBINATION (FOXP3); GO REGULATION OF CELL ACTIVATION (FOXP3); GO T HELPER 17 TYPE IMMUNE RESPONSE (FOXP3); GO REGULATION OF CELL CELL ADHESION (FOXP3); GO T CELL TOLERANCE INDUCTION (FOXP3); GO NEGATIVE REGULATION OF CANONICAL NF KAPPAB SIGNAL TRANSDUCTION (CCDC22); GO REGULATORY T CELL DIFFERENTIATION (FOXP3); GO T CELL RECEPTOR SIGNALING PATHWAY (FOXP3); GO IMMUNE RESPONSE REGULATING SIGNALING PATHWAY (FOXP3); GO T CELL SELECTION (FOXP3); GO POSITIVE REGULATION OF UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (CCDC22); GO INFLAMMATORY RESPONSE (FOXP3); GO IMMUNE RESPONSE REGULATING CELL SURFACE RECEPTOR SIGNALING PATHWAY (FOXP3); GO IMMUNOGLOBULIN PRODUCTION INVOLVED IN IMMUNOGLOBULIN MEDIATED IMMUNE RESPONSE (FOXP3); GO REGULATION OF TOLERANCE INDUCTION (FOXP3); GO MONONUCLEAR CELL DIFFERENTIATION (FOXP3); GO T CELL MEDIATED IMMUNITY (FOXP3); GO T CELL PROLIFERATION (FOXP3); GO T HELPER 17 CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF ADAPTIVE IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF T CELL TOLERANCE INDUCTION (FOXP3); GO REGULATION OF T HELPER CELL DIFFERENTIATION (FOXP3); GO POSITIVE REGULATION OF PROTEOLYSIS (CCDC22); GO POSITIVE REGULATION OF PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (CCDC22); GO HOMEOSTATIC PROCESS (CCDC22, FOXP3); GO POSITIVE REGULATION OF TRANSFORMING GROWTH FACTOR BETA PRODUCTION (FOXP3); GO POSITIVE REGULATION OF TRANSFORMING GROWTH FACTOR BETA1 PRODUCTION (FOXP3); GO REGULATION OF T CELL ACTIVATION (FOXP3); GO HOMEOSTASIS OF NUMBER OF CELLS (FOXP3); GO ADAPTIVE IMMUNE RESPONSE (FOXP3); GO RESPONSE TO BACTERIUM (FOXP3); GO ADAPTIVE IMMUNE RESPONSE BASED ON SOMATIC RECOMBINATION OF IMMUNE RECEPTORS BUILT FROM IMMUNOGLOBULIN SUPERFAMILY DOMAINS (FOXP3); GO INTERLEUKIN 6 PRODUCTION (FOXP3); GO REGULATION OF CHRONIC INFLAMMATORY RESPONSE (FOXP3); GO VESICLE MEDIATED TRANSPORT TO THE PLASMA MEMBRANE (CCDC22); GO INTERLEUKIN 5 PRODUCTION (FOXP3); GO INTERLEUKIN 4 PRODUCTION (FOXP3); GO REGULATION OF T HELPER 17 TYPE IMMUNE RESPONSE (FOXP3); GO RESPONSE TO ALCOHOL (FOXP3); GO REGULATION OF T HELPER 17 CELL DIFFERENTIATION (FOXP3); GO INTERLEUKIN 17 PRODUCTION (FOXP3); GO REGULATION OF T CELL PROLIFERATION (FOXP3); GO REGULATION OF T CELL MEDIATED IMMUNITY (FOXP3); GO NEGATIVE REGULATION OF ALPHA BETA T CELL ACTIVATION (FOXP3); GO REGULATION OF UBIQUITIN DEPENDENT PROTEIN CATABOLIC PROCESS (CCDC22); GO POSITIVE REGULATION OF REGULATORY T CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF ALPHA BETA T CELL PROLIFERATION (FOXP3); GO INTERLEUKIN 10 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF ACTIVATED T CELL PROLIFERATION (FOXP3); GO POSITIVE REGULATION OF TRANSCRIPTION BY RNA POLYMERASE II (FOXP3); GO INTERLEUKIN 2 PRODUCTION (FOXP3); GO VESICLE MEDIATED TRANSPORT (CCDC22); GO NEGATIVE REGULATION OF ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO POSITIVE REGULATION OF RNA METABOLIC PROCESS (FOXP3); GO HEMOPOIESIS (FOXP3); GO CYTOKINE PRODUCTION (FOXP3); GO COPPER ION HOMEOSTASIS (CCDC22); GO REGULATION OF CELL POPULATION PROLIFERATION (FOXP3); GO REGULATION OF DNA BINDING TRANSCRIPTION FACTOR ACTIVITY (CCDC22, FOXP3); GO NEGATIVE REGULATION OF B CELL ACTIVATION (FOXP3); GO POSITIVE REGULATION OF T CELL MEDIATED IMMUNITY (FOXP3); GO RESPONSE TO ETHER (FOXP3); GO NITROGEN COMPOUND TRANSPORT (CCDC22); GO INTRACELLULAR SIGNALING CASSETTE (CCDC22); GO REGULATION OF CELL DEVELOPMENT (FOXP3); GO DEFENSE RESPONSE (FOXP3); GO NEGATIVE REGULATION OF B CELL MEDIATED IMMUNITY (FOXP3); GO POSITIVE REGULATION OF T CELL PROLIFERATION (FOXP3); GO MYELOID CELL HOMEOSTASIS (FOXP3); GO INTRACELLULAR TRANSPORT (CCDC22); GO REGULATION OF CELL DIFFERENTIATION (FOXP3); GO REGULATION OF DNA METABOLIC PROCESS (FOXP3); GO POSITIVE REGULATION OF PROTEIN METABOLIC PROCESS (CCDC22); GO ACTIVATED T CELL PROLIFERATION (FOXP3); GO CYTOKINE PRODUCTION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF TOLERANCE INDUCTION (FOXP3); GO MULTICELLULAR ORGANISMAL LEVEL HOMEOSTASIS (FOXP3); GO REGULATION OF DEFENSE RESPONSE (FOXP3); GO CYTOPLASMIC SEQUESTERING OF NF KAPPAB (CCDC22); GO CYTOPLASMIC SEQUESTERING OF PROTEIN (CCDC22); GO ORGANONITROGEN COMPOUND CATABOLIC PROCESS (CCDC22); GO REGULATION OF DEFENSE RESPONSE TO VIRUS (FOXP3); GO ACTIVATION OF IMMUNE RESPONSE (FOXP3); GO ALPHA BETA T CELL ACTIVATION (FOXP3); GO ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO POSITIVE REGULATION OF SIGNALING (CCDC22); GO ALPHA BETA T CELL PROLIFERATION (FOXP3); GO INORGANIC ION HOMEOSTASIS (CCDC22); GO CYTOPLASMIC SEQUESTERING OF TRANSCRIPTION FACTOR (CCDC22); GO T CELL DIFFERENTIATION (FOXP3); GO REGULATION OF LYMPHOCYTE DIFFERENTIATION (FOXP3); GO REGULATION OF IMMUNE EFFECTOR PROCESS (FOXP3); GO POSITIVE REGULATION OF CELL POPULATION PROLIFERATION (FOXP3); GO POSITIVE REGULATION OF LYMPHOCYTE ANERGY (FOXP3); GO REGULATION OF PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (CCDC22); GO REGULATION OF PROTEOLYSIS (CCDC22); GO CANONICAL NF KAPPAB SIGNAL TRANSDUCTION (CCDC22); GO NEGATIVE REGULATION OF PRODUCTION OF MOLECULAR MEDIATOR OF IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF LEUKOCYTE PROLIFERATION (FOXP3); GO NEGATIVE REGULATION OF HEMOPOIESIS (FOXP3); GO CELL CELL ADHESION (FOXP3); GO POSITIVE REGULATION OF LYMPHOCYTE DIFFERENTIATION (FOXP3); GO MACROMOLECULE CATABOLIC PROCESS (CCDC22); GO POSITIVE REGULATION OF LEUKOCYTE CELL CELL ADHESION (FOXP3); GO CELL ADHESION (FOXP3); GO CELL ACTIVATION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO CELL ACTIVATION (FOXP3); GO ENDOSOMAL TRANSPORT (CCDC22); GO ENDOTHELIAL CELL DEVELOPMENT (FOXP3); GO NEGATIVE REGULATION OF IMMUNE EFFECTOR PROCESS (FOXP3); GO NEGATIVE REGULATION OF IMMUNE RESPONSE (FOXP3); GO NEGATIVE REGULATION OF IMMUNE SYSTEM PROCESS (FOXP3); GO POSITIVE REGULATION OF LEUKOCYTE MEDIATED IMMUNITY (FOXP3); GO REGULATION OF MULTICELLULAR ORGANISMAL DEVELOPMENT (FOXP3); GO ENDOCYTIC RECYCLING (CCDC22); GO NEGATIVE REGULATION OF GENE EXPRESSION (FOXP3); GO LYMPHOCYTE ACTIVATION (FOXP3); GO LYMPHOCYTE ACTIVATION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF CD4 POSITIVE ALPHA BETA T CELL ACTIVATION (FOXP3); GO POSITIVE REGULATION OF CD4 POSITIVE ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO LYMPHOCYTE ANERGY (FOXP3); GO REGULATION OF RESPONSE TO BIOTIC STIMULUS (FOXP3); GO LYMPHOCYTE DIFFERENTIATION (FOXP3); GO LYMPHOCYTE HOMEOSTASIS (FOXP3); GO LYMPHOCYTE MEDIATED IMMUNITY (FOXP3); GO REGULATION OF MOLECULAR FUNCTION (CCDC22, FOXP3); GO PROTEIN DNA COMPLEX ORGANIZATION (FOXP3); GO POSITIVE REGULATION OF CELL ACTIVATION (FOXP3); GO POSITIVE REGULATION OF CELL ADHESION (FOXP3); GO B CELL ACTIVATION (FOXP3); GO B CELL ACTIVATION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF CELL CELL ADHESION (FOXP3); GO B CELL HOMEOSTASIS (FOXP3); GO B CELL MEDIATED IMMUNITY (FOXP3); GO CELL FATE COMMITMENT (FOXP3); GO POSITIVE REGULATION OF CELL DEVELOPMENT (FOXP3); GO POSITIVE REGULATION OF CELL DIFFERENTIATION (FOXP3); GO POSITIVE REGULATION OF CYTOKINE PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF IMMUNOGLOBULIN PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INFLAMMATORY RESPONSE (FOXP3); GO MAINTENANCE OF LOCATION (CCDC22); GO PROTEOLYSIS (CCDC22); GO POSITIVE REGULATION OF HEMOPOIESIS (FOXP3); GO EPITHELIAL CELL DEVELOPMENT (FOXP3); GO NEGATIVE REGULATION OF LEUKOCYTE CELL CELL ADHESION (FOXP3); GO REGULATION OF PRODUCTION OF MOLECULAR MEDIATOR OF IMMUNE RESPONSE (FOXP3); GO PROTEIN TRANSPORT (CCDC22); GO CELLULAR HOMEOSTASIS (CCDC22); GO NEGATIVE REGULATION OF MULTICELLULAR ORGANISMAL PROCESS (FOXP3); GO EPITHELIAL CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF LEUKOCYTE MEDIATED IMMUNITY (FOXP3); GO ESTABLISHMENT OF PROTEIN LOCALIZATION (CCDC22); GO NEGATIVE REGULATION OF LEUKOCYTE PROLIFERATION (FOXP3); GO NEGATIVE REGULATION OF MOLECULAR FUNCTION (CCDC22, FOXP3); GO ESTABLISHMENT OF LOCALIZATION IN CELL (CCDC22); GO ESTABLISHMENT OF ENDOTHELIAL BARRIER (FOXP3); GO NEGATIVE REGULATION OF LYMPHOCYTE ACTIVATION (FOXP3); GO ESTABLISHMENT OF BLOOD BRAIN BARRIER (FOXP3); GO NEGATIVE REGULATION OF LYMPHOCYTE DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF LYMPHOCYTE MEDIATED IMMUNITY (FOXP3); GO EPITHELIUM DEVELOPMENT (FOXP3); GO POSITIVE REGULATION OF GENE EXPRESSION (FOXP3); GO PROTEOLYSIS INVOLVED IN PROTEIN CATABOLIC PROCESS (CCDC22); GO POSITIVE REGULATION OF CATABOLIC PROCESS (CCDC22); GO CD4 POSITIVE OR CD8 POSITIVE ALPHA BETA T CELL LINEAGE COMMITMENT (FOXP3); GO CD4 POSITIVE ALPHA BETA T CELL PROLIFERATION (FOXP3); GO POSITIVE REGULATION OF INTRACELLULAR SIGNAL TRANSDUCTION (CCDC22); GO ENDOTHELIUM DEVELOPMENT (FOXP3); GO MAINTENANCE OF PROTEIN LOCATION (CCDC22); GO POSITIVE REGULATION OF INTERLEUKIN 4 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 10 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 17 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF NUCLEOBASE CONTAINING COMPOUND METABOLIC PROCESS (FOXP3); GO POSITIVE REGULATION OF DEVELOPMENTAL PROCESS (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 2 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 4 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 5 PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF INTERLEUKIN 6 PRODUCTION (FOXP3); GO SOMATIC DIVERSIFICATION OF IMMUNOGLOBULINS (FOXP3); GO SOMATIC DIVERSIFICATION OF IMMUNE RECEPTORS (FOXP3); GO NEGATIVE REGULATION OF INTRACELLULAR SIGNAL TRANSDUCTION (CCDC22); GO POSITIVE REGULATION OF IMMUNE SYSTEM PROCESS (FOXP3); GO POSITIVE REGULATION OF IMMUNE RESPONSE (FOXP3); GO POSITIVE REGULATION OF IMMUNE EFFECTOR PROCESS (FOXP3); GO POSITIVE REGULATION OF IMMATURE T CELL PROLIFERATION (FOXP3); GO CD4 POSITIVE ALPHA BETA T CELL ACTIVATION (FOXP3); GO CD4 POSITIVE ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO CD4 POSITIVE CD25 POSITIVE ALPHA BETA REGULATORY T CELL DIFFERENTIATION (FOXP3); GO T CELL CYTOKINE PRODUCTION (FOXP3); GO REGULATION OF RESPONSE TO EXTERNAL STIMULUS (FOXP3); GO NEGATIVE REGULATION OF RESPONSE TO EXTERNAL STIMULUS (FOXP3); GO ANTIGEN RECEPTOR MEDIATED SIGNALING PATHWAY (FOXP3); GO NEGATIVE REGULATION OF CELL DEVELOPMENT (FOXP3); GO REGULATION OF ISOTYPE SWITCHING (FOXP3); GO REGULATION OF ISOTYPE SWITCHING TO IGE ISOTYPES (FOXP3); GO NEGATIVE REGULATION OF CELL DIFFERENTIATION (FOXP3); GO RESPONSE TO LIPID (FOXP3); GO DNA METABOLIC PROCESS (FOXP3); GO CHROMATIN REMODELING (FOXP3); GO NEGATIVE REGULATION OF CELL POPULATION PROLIFERATION (FOXP3); GO RESPONSE TO KETONE (FOXP3); GO DNA RECOMBINATION (FOXP3); GO REGULATION OF LEUKOCYTE DIFFERENTIATION (FOXP3); GO REGULATION OF LEUKOCYTE MEDIATED IMMUNITY (FOXP3); GO REGULATION OF B CELL ACTIVATION (FOXP3); GO REGULATION OF LEUKOCYTE PROLIFERATION (FOXP3); GO MODIFICATION DEPENDENT MACROMOLECULE CATABOLIC PROCESS (CCDC22); GO RESPONSE TO MOLECULE OF BACTERIAL ORIGIN (FOXP3); GO POST GOLGI VESICLE MEDIATED TRANSPORT (CCDC22); GO TRANSFORMING GROWTH FACTOR BETA PRODUCTION (FOXP3); GO TRANSFORMING GROWTH FACTOR BETA1 PRODUCTION (FOXP3); GO REGULATION OF B CELL MEDIATED IMMUNITY (FOXP3); GO CHRONIC INFLAMMATORY RESPONSE (FOXP3); GO POSITIVE T CELL SELECTION (FOXP3); GO NEGATIVE REGULATION OF CELL CELL ADHESION (FOXP3); GO REGULATION OF IMMUNE RESPONSE (FOXP3); GO REGULATION OF IMMUNE SYSTEM PROCESS (FOXP3); GO T CELL ACTIVATION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO T CELL ACTIVATION (FOXP3); GO REGULATION OF IMMUNOGLOBULIN PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF CD4 POSITIVE ALPHA BETA T CELL ACTIVATION (FOXP3); GO GOLGI TO PLASMA MEMBRANE TRANSPORT (CCDC22); GO REGULATION OF INFLAMMATORY RESPONSE (FOXP3); GO NEGATIVE REGULATION OF CD4 POSITIVE ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO TYPE II INTERFERON PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF CD4 POSITIVE ALPHA BETA T CELL PROLIFERATION (FOXP3); GO REGULATION OF CD4 POSITIVE CD25 POSITIVE ALPHA BETA REGULATORY T CELL DIFFERENTIATION (FOXP3); GO REGULATION OF CD4 POSITIVE ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO REGULATION OF CD4 POSITIVE ALPHA BETA T CELL ACTIVATION (FOXP3); GO TUMOR NECROSIS FACTOR SUPERFAMILY CYTOKINE PRODUCTION (FOXP3); GO MONOATOMIC ION HOMEOSTASIS (CCDC22); GO REGULATION OF CATABOLIC PROCESS (CCDC22); GO ISOTYPE SWITCHING TO IGG ISOTYPES (FOXP3); GO NEGATIVE REGULATION OF CELL ACTIVATION (FOXP3); GO REGULATION OF INTRACELLULAR SIGNAL TRANSDUCTION (CCDC22); GO NEGATIVE REGULATION OF CELL ADHESION (FOXP3); GO NEGATIVE REGULATION OF T HELPER CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF T HELPER 17 TYPE IMMUNE RESPONSE (FOXP3); GO NEGATIVE REGULATION OF T CELL PROLIFERATION (FOXP3); GO NEGATIVE REGULATION OF T CELL MEDIATED IMMUNITY (FOXP3); GO POSITIVE REGULATION OF ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF DEFENSE RESPONSE TO VIRUS (FOXP3); GO RESPONSE TO RAPAMYCIN (FOXP3); GO NEGATIVE REGULATION OF DEVELOPMENTAL PROCESS (FOXP3); GO NEGATIVE REGULATION OF DNA BINDING TRANSCRIPTION FACTOR ACTIVITY (CCDC22, FOXP3); GO POSITIVE REGULATION OF MULTICELLULAR ORGANISMAL PROCESS (FOXP3); GO NEGATIVE REGULATION OF DNA METABOLIC PROCESS (FOXP3); GO NEGATIVE REGULATION OF DNA RECOMBINATION (FOXP3); GO LOCALIZATION WITHIN MEMBRANE (CCDC22); GO CENTRAL NERVOUS SYSTEM DEVELOPMENT (FOXP3); GO REGULATION OF ALPHA BETA T CELL DIFFERENTIATION (FOXP3); GO REGULATION OF ALPHA BETA T CELL ACTIVATION (FOXP3); GO BIOLOGICAL PROCESS INVOLVED IN INTERSPECIES INTERACTION BETWEEN ORGANISMS (FOXP3); GO RESPONSE TO VIRUS (FOXP3); GO NEGATIVE REGULATION OF SIGNALING (CCDC22); GO PROTEIN CATABOLIC PROCESS (CCDC22); GO REGULATION OF ADAPTIVE IMMUNE RESPONSE (FOXP3); GO NEGATIVE REGULATION OF RNA BIOSYNTHETIC PROCESS (FOXP3); GO REGULATION OF RESPONSE TO STRESS (FOXP3); GO POSITIVE REGULATION OF CANONICAL NF KAPPAB SIGNAL TRANSDUCTION (CCDC22); GO NEGATIVE REGULATION OF RESPONSE TO STIMULUS (CCDC22, FOXP3); GO POSITIVE REGULATION OF ALPHA BETA T CELL ACTIVATION (FOXP3); GO NEGATIVE REGULATION OF RESPONSE TO BIOTIC STIMULUS (FOXP3); GO NEGATIVE REGULATION OF DEFENSE RESPONSE (FOXP3); GO POSITIVE REGULATION OF ADAPTIVE IMMUNE RESPONSE (FOXP3); GO RESPONSE TO NITROGEN COMPOUND (FOXP3); GO NEGATIVE REGULATION OF T CELL DIFFERENTIATION (FOXP3); GO NEGATIVE REGULATION OF T CELL CYTOKINE PRODUCTION (FOXP3); GO RESPONSE TO ORGANIC CYCLIC COMPOUND (FOXP3); GO LEUKOCYTE CELL CELL ADHESION (FOXP3); GO NEGATIVE REGULATION OF TYPE II INTERFERON PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF TUMOR NECROSIS FACTOR SUPERFAMILY CYTOKINE PRODUCTION (FOXP3); GO LEUKOCYTE DIFFERENTIATION (FOXP3); GO LEUKOCYTE HOMEOSTASIS (FOXP3); GO RESPONSE TO OXYGEN CONTAINING COMPOUND (FOXP3); GO REGULATION OF LYMPHOCYTE ACTIVATION (FOXP3); GO LEUKOCYTE MEDIATED IMMUNITY (FOXP3); GO REGULATION OF LYMPHOCYTE MEDIATED IMMUNITY (FOXP3); GO LEUKOCYTE PROLIFERATION (FOXP3); GO CHEMICAL HOMEOSTASIS (CCDC22); GO TOLERANCE INDUCTION TO SELF ANTIGEN (FOXP3); GO TOLERANCE INDUCTION DEPENDENT UPON IMMUNE RESPONSE (FOXP3); GO TOLERANCE INDUCTION (FOXP3); GO NEGATIVE REGULATION OF TRANSCRIPTION BY RNA POLYMERASE II (FOXP3); GO NEGATIVE REGULATION OF CYTOKINE PRODUCTION (FOXP3); GO NEGATIVE REGULATION OF CYTOKINE PRODUCTION INVOLVED IN IMMUNE RESPONSE (FOXP3); GO PRODUCTION OF MOLECULAR MEDIATOR OF IMMUNE RESPONSE (FOXP3); GO NEGATIVE REGULATION OF NF KAPPAB TRANSCRIPTION FACTOR ACTIVITY (CCDC22, FOXP3)",
  Summary: "This 256bp region is characterized by a weak enhancer element harboring an AP-2 transcription factor motif, residing in a larger domain of interferon-regulatory factor (IRF) protein binding sites and lymphoid DHSs. Co-located with the FOXP3 gene, an important immune system regulator."
  `

  const abstractsSection = `Abstracts
  --------
  {% for abstract in abstracts %}
  Title: {{ abstract.full_title }}
  Abstract: {{ abstract.abstract }}

  {% endfor %}
  `

  const taskSection = `Task
  --------

  Query: {{ query}}
  Summary:
  `

  const defaultPrompt = `${termsSection}
  ${abstractsAccess}
  ${tastSection}
  ${examplesSection}
  ${abstractsSection}
  ${taskSection}
  `.trim().split('\n').map(line => line.trimStart()).join('\n');

  // Function to include/exclude abstracts in the prompt
  const toggleIncludeAbstracts = (include) => {
    set({ abstractsIncluded: include })
    let newPrompt = include ? 
      `${termsSection}
      ${abstractsAccess}
      ${tastSection}
      ${examplesSection}
      ${abstractsSection}
      ${taskSection}`.trim().split('\n').map(line => line.trimStart()).join('\n')
    : 
    `${termsSection}
      ${tastSection}
      ${examplesSection}
      ${taskSection}`.trim().split('\n').map(line => line.trimStart()).join('\n')
    
    set({ prompt: newPrompt })
    get().generateSummaryFromQuery(newPrompt)
  }

  return {
    query: "",
    setQuery: (query) => set({ query }),
    showQuery: false,
    setShowQuery: (show) => set({ showQuery: show }),
    showPromptEditor: false,
    setShowPromptEditor: (show) => set({ showPromptEditor: show }),
    summaryLoading: false,
    setSummaryLoading: (loading) => set({ summaryLoading: loading }),
    request_id: null,
    setRequest_id: (id) => set({ request_id: id }),
    regionSummary: "",
    setRegionSummary: (regionSummary) => set({ regionSummary }),
    abstracts: [],
    setAbstracts: (abstracts) => set({ abstracts }),
    generateQueryFromNarration,
    generateSummaryFromQuery,
    feedback,
    defaultPrompt,
    prompt: defaultPrompt,
    setPrompt: (prompt) => set({ prompt }),
    toggleIncludeAbstracts,
    abstractsIncluded: true,
    setAbstractsIncluded: (included) => set({ abstractsIncluded: included }),
    url: `/api/pubmedSummary/pubmed_summary`,
    url_feedback: `/api/pubmedSummary/feedback`
  }
}

export default SummaryGeneration;